services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/go:1-1.25-bookworm
    volumes:
      - ..:/workspace:cached
    environment:
      PGHOST: postgres
      PGPORT: "5432"
      PGUSER: ekaya
      PGPASSWORD: localdev
      PGDATABASE: ekaya_engine
      AUTH_ENABLE_VERIFICATION: "false"
    command: sleep infinity
    depends_on:
      - postgres
    network_mode: service:postgres
